services:
  backend:
    build: .
    command: bash -c ''
    volumes:
      - .:/prop_bet_backend
    # ports:
    #   - 8008:8000
    environment:
      - DATABASE_URL=postgresql://admin:adminpassword@db:5432/prop_bet
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminpassword
      - POSTGRES_DB=prop_bet

volumes:
  postgres_data:
